services:
    nginx:
        container_name: textmagic_nginx
        image: nginx:latest
        volumes:
            - ./public:/app/public
            - ./var/log/:/logs/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 11001:80
        restart: unless-stopped
    php:
        container_name: textmagic_php
        build:
            dockerfile: docker/php/Dockerfile
            context: .
            target: app_php
        restart: unless-stopped
        volumes:
            - ./fs:/app/fs
        environment:
            DATABASE_URL: pgsql://textmagic:gfhjkm@db/textmagic?serverVersion=13&charset=utf8
            REDIS_URL: redis://redis
            REDIS_URL_SESSION: redis://redis
            REDIS_URL_DOCTRINE: redis://redis
        healthcheck:
            test: healthcheck
            interval: 10s
            timeout: 3s
            retries: 3
        depends_on:
            redis:
                condition: service_started
            db:
                condition: service_healthy
    db:
        image: postgres:13
        ports:
            - '11002:5432'
        container_name: textmagic_pgsql
        restart: unless-stopped
        environment:
            POSTGRES_DB: 'textmagic'
            POSTGRES_USER: 'textmagic'
            POSTGRES_PASSWORD: 'gfhjkm'
        volumes:
            - pgdata:/var/lib/postgresql/data:rw
        healthcheck:
            test: pg_isready -d textmagic -U textmagic
            interval: 10s
            timeout: 3s
            retries: 3
    redis:
        image: redis:7.2.0
        container_name: textmagic_redis
        restart: unless-stopped
        ports:
            - 11004:6379
volumes:
    pgdata:
        labels:
            - keep
